server:
  port: 8083
  
spring:
  application:
    name: zuulservice

zuul:
  #prefix: /api
  host:
    socket-timeout-millis: 300000
  routes:
    userservice:
      path: /user/**
      serviceId: userservice
    accountservice:
      path: /account/**
      serviceId: accountservice
      
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    hostname: localhost
    